### ISSUE TITLE
Add location setting

### ISSUE THREAD

**Issue by alexa-griffin** [BurnySc2/BurnysTSBC#8]
## description
For those with "short" screens the UI will cut off especially when using other mods

## Expected behavior
The UI will not cut off when the screen is too short
## Observed behavior 
The modal cuts off vertically when using other mods or when the user's screen is too short
![deras](https://user-images.githubusercontent.com/22418744/50549602-ae5e7b80-0c2d-11e9-98bf-82d598025c5b.PNG)

## Possible fixes
- add a setting that changes the modal location
- make the modal's position able to be dragged by the user
-  make the UI scrollable

**Comment by BurnySc2** [comment]
Thanks for the detailed bug description!

I have very little interest to update the mod files at the moment.

However, I made a replicate of this mod as a javascript version (to circumvent multiplayer factorio games that do not have the mod installed). This should also "fix" the issue that you describe, since it runs in the browser.

It is accessable here and should have the same functionality as the mod: https://burnysc2.github.io/Factorio/Tools/BurnysTSBC/

**Comment by alexa-griffin** [comment]
That works thanks I was going to use it for a seablock playthrough but fnei was a bad
